### ISSUE TITLE
play_motion2 package missing from third_parties.repos

### ISSUE THREAD

**Issue by pdingemans** [fmrico/book_ros2#16]
# Important!!!
- [ x] I have checked that this issue/bug/fix/correction has not been already created before in open or closed issues.

# Type of bug
- [ ] A) Typo/error in Figure/text
- [ x] B) Bug in code
- [ ] C) General comment, recommendation or petition 

# Issue Description
The tiago build is failing due to missing play_motion2 msgs. 
Caused by missing package in the mentioned .repos file.

## Proposal
Add following lines to .repos file
 
ThirdParty/play_motion2:
    type: git
    url: https://github.com/pal-robotics/play_motion2
    version: humble-devel

## how to reproduce
Follow step from chapter1 (pdf)
failing on : 
colcon build--symlink-install

## Expected behavior
build must pass with no errors.

## Desktop
 - OS: [Ubuntu 22.04]
 - ROS2 Distro : Humble

**Comment by fmrico** [comment]
Yes!! It is a known problem introduced the las week. @juancams, how did you fix it last week?

**Comment by Juancams** [comment]
Hi @pdingemans 

Pal robotics introduced a new package to be able to move the arm when spawning the robot. It's going to be in the ros install soon, so it's not intended to be put inside a .repos.

I would recommend you not to update ros2_control, since they have added a small bug that breaks everything. In the event that you have updated and the simulation did not run correctly, contact us and we will tell you about the patch that you have to add.

^^

**Comment by pdingemans** [comment]
Hi @Juancams 
I'd be interested in the patch  as the simulation does not react to the keyboard.

Something else: thanks for providing the book and examples. It'll provide a great starting point for our students.

**Comment by nilutpolkashyap** [comment]
Hi @pdingemans you can refer to [pal-robotics/pmb2_simulation#4](https://github.com/pal-robotics/pmb2_simulation/issues/4). I was facing the same problem where my simulation robot was not moving. 

Compiling the gazebo_ros2_control humble branch and ros2_control humble branch in your local workspace will solve the problem.
